package org.carewebframework.shell.ancillary;

import org.carewebframework.shell.elements.UIElementBase;

/**
 * Allows one element to listen for produced generated by another element.
 */
public interface INotificationListener {
    
    /**
     * Notifies the listener of an event.
     * 
     * @param sender The sender of the event.
     * @param eventName The event name.
     * @param eventData The event data.
     * @return If returns false, the propagation chain is stopped.
     */
    boolean onNotification(UIElementBase sender, String eventName, Object eventData);
}